version: "3.8"

services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack-prod
    command: redis-stack-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_ARGS=--appendonly yes --appendfsync everysec
      - REDISEARCH_ARGS=THREADS 16
      - REDISJSON_ARGS=MAXMEMORY 48gb
    volumes:
      - redis_data:/data
      - ./redis.conf:/redis-stack.conf
    ports:
      - "6379:6379" # Redis port
      - "8001:8001" # RedisInsight port
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          cpus: "12"
          memory: 64G
        reservations:
          cpus: "8"
          memory: 32G
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - redis-net

volumes:
  redis_data:
    driver: local

networks:
  redis-net:
    driver: bridge
